apiVersion: v1 
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    app: voting-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004 
  selector:
    name: result-app-pod
    app: voting-app